//Action types
export const CHANGE_TABLE_NUMBER = 'CHANGE_TABLE_NUMBER';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';